name: entomologo CI

#esta linea abre la linea de procesos que quiero automatizar.
on:
  #indica la accion sobre la que quiero trabajar en est caso un push
  push:
    branches: ["HU_CI_CD"]
  pull_request:
    branches: ["HU_CI_CD"]

#Indica los trabajos que quiero que se realizen
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build app
        run: ./gradlew assemble

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmasnr/android-test-report-action@v1.2.0
        if: ${{always()}}